### ISSUE TITLE
Suggestion to add Simple Scraper to Web Scrapers

### ISSUE THREAD

**Issue by appodeepa** [benjaminchowpetit/awesome-curated-tools#2]
Hey, super useful list. 

Thoughts on adding Simple Scraper (https://simplescraper.io) to the 'Web scrapers' section?  Or should I create a pull request? 

Cheers

**Comment by benjaminchowpetit** [comment]
Hello,

Thank you for your feedback and for this useful tool ! We added it.

...and happy new year too !

**Comment by appodeepa** [comment]
@benjaminchowpetit awesome, glad you find it useful. Happy new year!
